### ISSUE TITLE
lazy provider selection

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/genomepy#101]
@Maarten-vd-Sande suggested the possibility to let genomepy pick a provider. We could implement a system where it loops over providers until an exact match is found for the genome (similar to what is done in our snakemake-workflows).

This would however mean *we* make a choice in provider order. It would also remove agency from the user, which is important due to the differences in format. 

Would this be acceptable @simonvh?

**Comment by simonvh** [comment]
This is possible yes, and I think I like this option. It would just pick the first one it finds, or we can specify provider priority. I think this would not necessarily take choice away from the user.
To me it would look something like this:

```
$ genomepy install coolgenome
Note: coolgenome is provided by more than one provider: Ensembl, NCBI.
Using Ensembl provider. Run genomepy with the -p option to explicitly specify the provider.
<Installing from Ensembl>
```

```
$ genomepy install coolgenome -p NCBI
<Install specifically from NCBI>
```

For me, order would be UCSC > Ensembl > NCBI.
