### ISSUE TITLE
Missing plugin should warn instead of error

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/genomepy#108]
I still had `sizes` listed as a plugin. In this case genomepy will crash with an error. It would probably be better if there's just a warning printed if a plugin is unknown.

**Comment by siebrenf** [comment]
Could you give a reproducible example?

I thought this would be an easy fix, but I cant reproduce the error even! I added sizes to the config file, and it gets listed with `genomepy plugin list` and `genomepy config show`. I can search and download genomes, alter other plugins, but no error :o

**Comment by siebrenf** [comment]
Closing for now
