### ISSUE TITLE
genomepy install from url with error

### ISSUE THREAD

**Issue by wangmhan** [vanheeringen-lab/genomepy#113]
Hi,

1) I tried first to install with command: genomepy install GRCg6a Ensembl --annotation,
but always came to error: urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>.

Then I turned to directly install with url: genomepy install ftp://ftp.ensembl.org/pub/release-97/fasta/gallus_gallus/dna/Gallus_gallus.GRCg6a.dna.toplevel.fa.gz url --localname gg6_genomepy.
This get: Exception: Unknown provider

I wonder if I could install downloaded fasta file? As if I directly download the fa.gz use wget, there is no problem.

2) Also would like to known if I could add custom gtf file as annotation. Thanks a lot!

best regards,
Menghan

**Comment by siebrenf** [comment]
Hey @wangmhan,

As to your main problem, my guess is your had connection issues with Ensembl. Try again now (it worked for me just now). 
What version of genomepy are you using? An older version will not recognize the URL provider, which may explain the exception. 

As to your second question: yes you can absolutely add a custom gtf file! Genomepy simply looks in the genome directory for a gtf file (gzipped or not), and assumes that is the matching annotation.

Let me know if the problems persist,
Siebren

**Comment by wangmhan** [comment]
Thanks for your reply.

I am using genomepy with version 0.5.5. And yes, after upgrade to 0.8.3,
now there is no problem!

best regards,
Menghan
