### ISSUE TITLE
Container Image (Docker/Singularity)???

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [vanheeringen-lab/genomepy#119]
Awesome tool! 

Are there any "official" images for this tool available? 

If not, are there plans to make an image for this tool?

**Comment by siebrenf** [comment]
Hey there @YogiOnBioinformatics, 

there's currently no plans for this. This might be a good opportunity for me to learn about both docker and github actions,  so I'll have a look :)
With the summer holidays looming, this might take a while though!

**Comment by siebrenf** [comment]
Seems this is doable. I managed to make a simple docker image: `siebrenf/genomepy:test_1`.

However, the insulation feature of docker makes is impossible for genomepy to create a persistent cache. As a result, provider details are retrieved anew every run. Additionally, the aim of genomepy is to install genomes, annotations and other data. These need to be copied out of the container for downstream processes.

If you have some pointers on how this should be done, or know of other packages that did this successfully, let me know!

**Comment by siebrenf** [comment]
turns out we already made images when uploading to bioconda (thx for the tip @simonvh!)

https://quay.io/repository/biocontainers/genomepy

**Comment by YogiOnBioinformatics** [comment]
oh wow! 

just so i understand, you submitted your software to bioconda and they containerized it?

**Comment by siebrenf** [comment]
Yes! [Seems](https://bioconda.github.io/contributor/build-system.html) they containerize all packages.

**Comment by YogiOnBioinformatics** [comment]
Awesome! Thanks very much.
