### ISSUE TITLE
Progress bars?

### ISSUE THREAD

**Issue by laserson** [vanheeringen-lab/genomepy#138]
Just used genomepy for the first time. (Great so far!) One minor feature that could be useful for users is to include some sort of progress bar. To start you could use the click spinner just to show progress, but otherwise you could also integrate tqdm so that you can get an estimate of how long the download will take, especially given your bandwidth.

**Comment by siebrenf** [comment]
Hi there,

it would indeed be nice to have some feedback, at least on the `install` function! I'll have a look when I have some free time. And thank you for the examples!
