### ISSUE TITLE
Filter sequences in the annotation file

### ISSUE THREAD

**Issue by jma1991** [vanheeringen-lab/genomepy#154]
I have noticed that when I filter sequences from the reference genome, the associated annotation file still contains sequences from the rest of the genome. Is there any scope to implement functionality to filter the annotation file as well? Some software I am using complains about missing sequences which are defined in the annotation file.

**Comment by siebrenf** [comment]
Hey jma, this is a good point!

I should make a dedicated annotation module for these sorts of functions. But for now the _annotation sanitizing_ can be expanded to drop contigs missing in the genome (in case you used regex filtering). I'll try to get this done soon!

Until then, this snippet should be able to apply the same regex filter on a gtf file.
```
import re
import shutil

def filter_gtf(ingtf, regex=".*", invert_match=False):
    outgtf = ingtf + ".tmp"
    with open(ingtf, "r") as oldgtf, open(outgtf, "w") as newgtf:
        for line in oldgtf:
            if (invert_match and not re.match(regex, line)) or \
                    (not invert_match and re.match(regex, line)):
                newgtf.write(line)
    shutil.move(outgtf, ingtf)
    return

filter_gtf("path/to/annotation.gtf", "chr")
```

**Comment by siebrenf** [comment]
Installing an annotation with genomepy 0.10 will now automatically remove missing contigs, unless specified.
We also implemented filter functions and an Annotation class of the API. Checkout the [docs](https://vanheeringen-lab.github.io/genomepy/_autosummary/genomepy.annotation.html#module-genomepy.annotation).
