### ISSUE TITLE
FR genomepy version in readme

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/genomepy#166]
See title.

**Comment by simonvh** [comment]
Just for my information: README on github? In the help on the command-line? Or in the genome README?

**Comment by Maarten-vd-Sande** [comment]
Ah my bad. In the genome folder README. 

I have a bunch of different assemblies downloaded, and I once got issues between one downloaded on server A and on downloaded on server B, because they were downloaded with different genomepy versions. Had to do with the `alt` regions being removed, but I _think_ if the genomepy version was recorded in the README I would have figured it out much earlier :smile: (the removal of alt regions is written down in the readme I know)
