### ISSUE TITLE
Mitochondrial genome

### ISSUE THREAD

**Issue by elichter** [vanheeringen-lab/genomepy#203]
Trying to search for the mouse mitochondrial genome (Reference Sequence: NC_005089.1). It cannot find it, also tried with the ACCESSION   AY172335. Any suggestions?

**Comment by siebrenf** [comment]
Its in the mouse genome, but renamed to MT!

You can download the whole genome and annotation with `genomepy install --provider ncbi GRCm39 --annotation`, or just the mitochondrial stuff with  `genomepy install --provider ncbi GRCm39 --regex MT --annotation`.

The download folder also contains the assembly report that was used to rename sequences from "NC_1234" to "chr1", "MT", etc. In here, you can find the original names for the mitochondral sequence:
```
Sequence-Name  Sequence-Role       Assigned-Molecule  Assigned-Molecule-Location/Type  GenBank-Accn  Relationship  RefSeq-Accn  Assembly-Unit  Sequence-Length  UCSC-style-name
MT             assembled-molecule  MT                 Mitochondrion                    AY172335.1    =             NC_005089.1  non-nuclear    16299            chrM
```
