### ISSUE TITLE
genomepy fails when downloading from UCSC

### ISSUE THREAD

**Issue by paumarc** [vanheeringen-lab/genomepy#213]
It has problems connecting to the  UCSC server
 
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'genome-mysql.soe.ucsc.edu:3306' (110)

**Comment by siebrenf** [comment]
It seems all of UCSC is down right now!

https://genome.ucsc.edu/

**Comment by siebrenf** [comment]
UCSC is back online! Your problems should have passed. If you are still experiencing issues with connecting to UCSC, have a look at #200.

Additionally, the next version of genomepy will give clearer feedback :)
