### ISSUE TITLE
instead of throwing gtfToGenePred errors it should tell user that they should be installed, otherwise users will think annotation download is broken

### ISSUE THREAD

**Issue by antonkulaga** [vanheeringen-lab/genomepy#225]
Whenever I try to download Ensembl genomes for human and mice I get:
```
/bin/sh: 1: gtfToGenePred: not found
```
For half and hour I thought that Ensembl support is broken. I believe the error message should explicitly say I should install some console tools. Or, actually it can allow downloading everything but gene-pred stuff, because it is often enough to just download gtf and process it yourself

**Comment by simonvh** [comment]
Hi @antonkulaga, can I ask how you installed genomepy? When you install genomepy via `conda`, then `gtfToGenePred` should be installed as a dependency. If you installed it via `pip`, then indeed you need to install some UCSC tools (as is described in the installation guide). I do agree that the message can be more informative when a required dependency is not found.

**Comment by siebrenf** [comment]
A more descriptive error will be raised with genomepy 0.15!
