### ISSUE TITLE
Partial matching for NCBI taxonomy identifiers is not great for automating genome retrieval

### ISSUE THREAD

**Issue by uniqueg** [vanheeringen-lab/genomepy#235]
I would like to automate the retrieval of genomes and annotations given an NCBI taxonomy identifier. While I can see that the fuzzy search implemented for `genomepy.search()` can be very useful in interactive use, it can be a bit of a pain for automated searching.

For example, if I search for `13146` on Ensembl, I currently get the following.

```console
          name   tax_id                                   species
bMelUnd1.mat.Z    13146                   Melopsittacus undulatus
        Cylto1  1314674  Cylindrobasidium torrendii FP15055 ss-10
        Ricme1  1314672                       Peniophora sp. CONT
        Leppa1  1314670       Lepidopterella palustris CBS 459.81
```

Of course, it is easy to enforce a full tax ID match on the client side, but perhaps an option to tweak the search behavior, e.g., (1) exact match, (2) only case and white space sanitization and (3) fuzzy, would make the tool more user friendly for use cases involving automated retrieval.

**Comment by siebrenf** [comment]
Great idea! I got exited and made a PR. Try it with
```
pip install git+https://github.com/vanheeringen-lab/genomepy.git@exact
```
