### ISSUE TITLE
genomepy does not work with mysql 9.0

### ISSUE THREAD

**Issue by biobai** [vanheeringen-lab/genomepy#249]
genomepy install hg19

mysql.connector.errors.DatabaseError: 2059 (HY000): Authentication plugin 'mysql_native_password' cannot be loaded: /usr/lib/mysql/plugin/mysql_native_password.so: cannot open shared object file: No such file or directory

```
conda list |grep mysql
mysql-common              9.0.1                h70512c7_0    conda-forge
mysql-connector-c         6.1.11            h659d440_1008    conda-forge
mysql-connector-python    9.0.0           py311h9c9ff8c_1    conda-forge
mysql-libs                9.0.1                ha479ceb_0    conda-forge
```
genomepy does not work with mysql 9.0.

**Comment by Maarten-vd-Sande** [comment]
For a quick fix, install the previous mysql-connector-python

With conda/mamba:

```
conda/mamba install mysql-connector-python=8.4.0
```
