### ISSUE TITLE
Add code/test coverage

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/genomepy#54]
This can be implemented (even on Master) between releases. It just must be done by a admin or owner.

[how-to](https://docs.codeclimate.com/docs/getting-started-with-code-climate)

**Comment by siebrenf** [comment]
I've run maintainability on my fork.

I'm noticing the threshold for a reprimand is... very low. Code is flagged with a single duplication of code. For instance:

```
def activate(name):
    """Activate plugin.
 
    Parameters
    ----------
```
occurs twice, and is flagged as a "major" issue. The good news is we have no more than 3x duplication anywhere :)

Files over 250 lines are flagged (provider.py and functions.py). We could split up provider.py per provider and generic functions. It wouldn't hurt at least.


https://codeclimate.com/github/siebrenf/genomepy

**Comment by simonvh** [comment]
Can't we tune this? This level of duplication warning is plain nonsense.

**Comment by siebrenf** [comment]
Seems we can! 

It seems however you really need to be the one to set it up, but we can fix all that tomorrow.
