### ISSUE TITLE
STAR indexing is enabled by default

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/genomepy#57]
This was turned on during an automated test and accidentally shipped in 0.7.0. 

If the user has star installed it will index a genome after downloading, which is not an intended default setting.

To disable, run `$ genomepy plugin disable star` once.

**Comment by siebrenf** [comment]
Working on a hotfix (0.7.1). 

Git flow claims to have released it, but Git and [Travis](https://travis-ci.org/vanheeringen-lab/genomepy/jobs/614677984) claim otherwise... 

it seems that either `git flow` does not like working with moved directories, or `travis` does not like working with `git flow`.

**Comment by siebrenf** [comment]
There's a problem when trying to update the bioconda-recipe ([PR](https://github.com/bioconda/bioconda-recipes/pull/18783), [error](https://circleci.com/gh/bioconda/bioconda-recipes/83145?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)). I believe(d) this may have had to do with moving the repo. 

First I changed the instance of github.com/simonvh/genomepy in the recipe to github.com/vanheerling-lab/genomepy. This didn't work. 

Then I found several inside our code, one in `setup.py`. Next I replaced all instances of github.com/simonvh/genomepy with the github.com/vanheerling-lab/genomepy (and pushed this to develop). I uploaded this to PyPi as genomepy-0.7.1a, downloaded the tarball and renamed it to 0.7.1. This was then placed in the 0.7.1-release downloads. Finally, the sha256sum on the recipe was updated.

Bioconda however still can't find the LICENSE file... 

P.S. This issue is already fixed for Pip users.

**Comment by simonvh** [comment]
You should not download the pypi tarball, but the tarball on the github release. I think you have deleted the MANIFEST file, and this means that files such as the LICENSE will now not be included in the pypi tarball. 

> Git flow claims to have released it, but Git and Travis claim otherwise...

> it seems that either git flow does not like working with moved directories, or travis does not like working with git flow.

Did you remember to push the tags?

**Comment by siebrenf** [comment]
Tags were pushed.

The wrong tarball/deleted MANIFEST might do the trick!

**Comment by siebrenf** [comment]
It worked! Bioconda should have version 0.7.1 soon!

**For those still on 0.7.0, you can deactivate plugins using `$ genomepy plugin disable PLUGIN`**


As for the MANIFEST. I had replaced this by putting the LICENSE and README in the `package_data`. According to [this stackoverflow](https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script), I should have put it in the data_files. I'll fix that in Develop.

I'll close this issue once bioconda has 0.7.1 available.

**Comment by siebrenf** [comment]
0.7.1 is now available on both pip and bioconda!
