### ISSUE TITLE
sanitize annotation

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/genomepy#60]
In [our snakemake workflow](https://github.com/vanheeringen-lab/snakemake-workflows/blob/0990c6280fbe6f3d502f8dbd7d2f95a91d167911/rules/get_genome.smk#L74) I made a script that that checks if the annotations use the same chromosome/scaffold names as the genome.fasta, and replaces them if not. We could add this functionality as a default to genomepy, and add a flag to skip this step.

**Comment by simonvh** [comment]
Yes, it would be very inconvenient if the annotation used different chromosome names?!
