### ISSUE TITLE
Is there a way to access the `.sizes` file via API

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/genomepy#79]
Previously you could do this via `.props`. However, this was cumbersome, and as the sizes plugin is removed, this doesn't work. Ideally there would be a consistent way to get (via the API) the name of files (the `gap.bed` file, the `.sizes` file, etc.).

for instance:

````
g = Genome("hg38")
g.sizes_file
```

**Comment by siebrenf** [comment]
indeed, this method should simple to implement now, and be available for the
*  sizes file
*  gaps file
*  gtf gile
*  bed file

**Comment by simonvh** [comment]
What would be a nice and consistent way to do this? Maybe also @Maarten-vd-Sande can chip in.

* `.get_sizes_file()`, `.get_gaps_file()`, etc.?
* `.get_file_location()` with `sizes`, `gaps` etc. as an argument?
* do we add the `get_` part or not?

**Comment by siebrenf** [comment]
pyfaidx uses
* self.filename for the genome
* self.indexname for the `.fai`

so we should use this scheme too? e.g.
* self.sizesname
* self.gapsname
* self.gtfannotionname
* self.bedannotionname

**Comment by siebrenf** [comment]
[quick n dirty](https://github.com/vanheeringen-lab/genomepy/commit/67d802cc9ada9b7cd8d8ea72b2ba5b6ddb50a368)

**Comment by simonvh** [comment]
I think using `@property` is a good idea. I also like being consistent with pyfaidx.
I do not like the lack of underscores for readability.

```
.sizes_name
.gaps_name
.gtf_annotation_name
.bed_annotation_name
```

or

```
.sizes_file
.gaps_file
.annotation_gtf_file
.annotation_bed_file
```

**Comment by Maarten-vd-Sande** [comment]
I would then go for  `_file`. 

I have not been following the recent (API) changes but I guess in 95% of the cases you access the files you actually want to access the underlying data. So maybe something to think about to also implement the `.sizes`, `.gaps`, `.annotation_gtf`, and `.annotation_bed` attributes. For `.sizes` you could  just return `{chr: len(seq) for chr, seq in self.items()}`. I am not sure what a natural way of representing gaps, gtfs, and beds is.

**Comment by simonvh** [comment]
This sounds good. `.datatype` and `.datatype_file` basically.

**Comment by siebrenf** [comment]
As of version 0.8, the Genome class now has the following properties/attributes that are populated on init:
```
self.genome_file 
self.genome_dir 
self.index_file 
self.sizes_file 
self.gaps_file 
self.annotation_gtf_file
self.annotation_bed_file
self.readme_file 
```

So you can now get the file paths like so:
```
g = Genome("hg38")
or
g = Genome("/path/to/hg38.fa")

g.sizes_file
```

please note the old `props` attribute has been renamed `plugin`, as it contains only plugin information (and some of the attributes are now properties).
