### ISSUE TITLE
write_readme permissions issue

### ISSUE THREAD

**Issue by fennerm** [vanheeringen-lab/genomepy#89]
We lock down write-permissions in our genome reference directory because the files are shared. Genomepy started failing with permissions errors in v0.8 because it's trying to update its README file.

Would it be possible to disable this feature if genomepy doesn't have write permission to the references directory?

**Comment by siebrenf** [comment]
[Looks like](https://docs.python.org/3/library/os.html#os.access) that should be doable! I'll add this in the next hotfix.

**Comment by fennerm** [comment]
Awesome thanks!
