### ISSUE TITLE
genomepy not finding all genomes

### ISSUE THREAD

**Issue by olgatsiouri1996** [vanheeringen-lab/genomepy#90]
I was looking for an organism in ensembl that exists with the name: Fusarium solani mpvi 77-13-4. I also was using an ncbi taxonomy id for both the organism and its family of genomes(Fusarium solani species complex with taxon id: 232080). While trying various ways that are specified in the program manual i could not find them.

**Comment by siebrenf** [comment]
Hey olga,

I've tried to look for your genome and can indeed not find "Fusarium solani mpvi 77-13-4". On NCBI I believe the genome is known under a [different name](https://www.ncbi.nlm.nih.gov/genome/?term=Nectria%20haematococca[Organism]&cmd=DetailsSearch). On Ensembl it's [here](https://fungi.ensembl.org/Fusarium_solani/Info/Index). This page seems to be in order, so I don't understand why it isn't showing up... I'll look into it!

For the moment, you can download the Ensembl genome and annotation from their direct URLs using the following command:

`genomepy install ftp://ftp.ensemblgenomes.org/pub/fungi/release-47/fasta/fusarium_solani/dna/Fusarium_solani.v2.0.dna_sm.toplevel.fa.gz url --url-to-annotation ftp://ftp.ensemblgenomes.org/pub/fungi/release-47/gff3/fusarium_solani/Fusarium_solani.v2.0.47.gff3.gz --localname Fusarium_solani.v2.0`

**Comment by siebrenf** [comment]
More news!

I've tracked your genome on Ensembl, and found out there is a mistake in the documentation of your species. **The above command is the only way to download it from Ensembl** until this is fixed on the Ensembl side.

If you're interested in the exact mistake: in the [the Ensembl fungal database](http://rest.ensembl.org/info/genomes/division/EnsemblFungi?content-type=application/json) you can find this information.

```
{"has_variations":0,"has_peptide_compara":1,"data_release_id":60,"assembly_name":"v2.0","has_synteny":1,"serotype":null,"assembly_ucsc":null,"has_genome_alignments":1,"url_name":"Fusarium_solani","assembly_level":"chromosome","base_count":51291997,"display_name":"Fusarium solani","assembly_accession":"GCA_000151355.1","strain":"MPVI 77-13-4","assembly_default":"v2.0","name":"fusarium_solani","taxonomy_id":660122,"species_taxonomy_id":140110,"organism_id":149,"is_reference":0,"division":"EnsemblFungi","has_pan_compara":0,"has_other_alignments":1,"genebuild":"2.0","assembly_id":150,"scientific_name":"Fusarium solani mpVI 77-13-4"}
```

The last field confirms this is your genome. The field `"assembly_name":"v2.0"` is supposed to be the unique name for the genome. Even worse, two other fungal genomes have the same name here, so genomepy overwrites the name "v2.0".

**Comment by siebrenf** [comment]
Same thing happened on NCBI: Assembly got saved under the name "v2.0". someone else made the same mistake. genomepy overwrote the non-unique name.

If you prefer the NCBI genome, you can download it directly using
```
genomepy install https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/151/355/GCF_000151355.1_v2.0/GCF_000151355.1_v2.0_genomic.fna.gz url --url-to-annotation https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/151/355/GCF_000151355.1_v2.0/GCF_000151355.1_v2.0_genomic.gff.gz --localname Fusarium_solani.v2.0
```
