### ISSUE TITLE
UCSC: matching genomes

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/genomepy#94]
Currently the assembly accession for UCSC genomes is scraped from the readme. It seems there is a more consistent way to do this:

https://genome.ucsc.edu/FAQ/FAQreleases.html#release3

Downside might be that mysql needs to be installed, or an alternative Python library such as [PyMySQL](https://github.com/PyMySQL/PyMySQL).

**Comment by siebrenf** [comment]
```
"""
mysql --user=genome --host=genome-mysql.soe.ucsc.edu -A -e 'desc asmEquivalent;' hgFixed

https://genome.ucsc.edu/FAQ/FAQreleases.html
https://mariadb.com/kb/en/getting-data-from-mariadb/
https://pynative.com/python-mysql-select-query-to-fetch-data/
"""
import mysql.connector


def get_closest_genome(genome, frm):
    cnx = mysql.connector.connect(
        host="genome-mysql.soe.ucsc.edu",
        user="genome",
        port=3306,
        database="hgFixed",
    )
    cur = cnx.cursor()
    cur.execute(f"SELECT destination, destinationAuthority FROM asmEquivalent WHERE source='{genome}' AND sourceAuthority='{frm}';")
    ret = cur.fetchall()

    cur.close()
    cnx.close()

    print(["destination", "destinationAuthority"])
    for row in ret:
        print(row)

    # cur.execute("desc asmEquivalent;")
    # cur.execute("SHOW DATABASES;")
    # cur.execute("SHOW TABLES;")
    # cur.execute("SHOW COLUMNS FROM asmEquivalent;")
    # print([c[0] for c in cur.fetchall()])
    # cur.execute("SELECT * FROM asmEquivalent;")

get_closest_genome(genome="sacCer3", frm="ucsc")
>>> ['destination', 'destinationAuthority']
>>> ('GCA_000146045.2_R64-1-1', 'genbank')
>>> ('GCF_000146045.2_R64', 'refseq')
>>> ('Saccharomyces_cerevisiae.R64-1-1', 'ensembl')
```

Seemed nice, so I tried it with this. 

We'd have to split the answers, and try to search each, then pick the best... Worst part is it seems not to work for genomes without an accession in the current system either, such as sacCer2.

**Comment by siebrenf** [comment]
Good news! 
Ensembl assemblies have this "genome.assembly" format, but all other sources use an "accession.assembly" format!
The smaller half of the UCSC genomes can be annotated with this!

Not only that, but the MySQL database can be asked _which gene annotations each genome has_. This is a gamechanger! Much faster searching, the potential to implement a `head` for each annotation available (not possible with the gz files).
